name: Rust Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update rust
      run: rustup update
    - name: install packaged dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libv4l-dev nasm libzmq3-dev capnproto libcapnp-dev
    - name: Build
      run: cd vmec-client && cargo build --verbose
    - name: Run tests
      run: cd vmec-client && cargo test --verbose common
